PATCH http://localhost:3001/users/5fd6137fb335d81174628682
Content-Type: application/json

{
    "0": {
        "_id": "5fda6e1ab773c41bf8339631",
        "seller": {
            "_id":"5fd6138fb335d81174628683",
            "userName": "hillobanaani"
        }
    },
    "1": {
        "_id": "5fda548beb0f0b2188d9caa3",
        "seller": {
            "_id": "5fd6138fb335d81174628683"
        }
    }
}
